env: "local"
ttl:
  access: 3m
  refresh: 24h
storages:
  redis_jwt: redis://192.168.0.175:6379/1
  redis_blacklist: redis://192.168.0.175:6379/2
  redis_user: redis://192.168.0.175:6379/3
logger:
  level: DEBUG
  show_path_call: false
ping_time: 1m
shutdown:
  period: 15s
  hard-period: 3s
readiness:
  drain_delay: 5s
